#!/bin/bash
cat > /etc/timezone <<-EOF
	Asia/Kuala_Lumpur
EOF
dpkg-reconfigure tzdata

cat > /etc/apt/apt.conf.d/90cache-proxy <<-EOF
	Acquire::http::Proxy "http://cache-proxy:3142";
EOF

apt-get update
apt-get install -y openjdk-7-jre-headless
apt-get clean

chown -R codekaki:codekaki /opt/birt
cp target/birt.war jetty/webapps
